### ISSUE TITLE
Crashes and Debug Versions of DLL's...

### ISSUE THREAD

**Issue by bsom** [Blagodarenko/miner-burst#1]
On occasion, the miner.exe will 'crash' with an error message but the console application itself continues to run.  I'm trying to collect screenshots of all of the varying ways it has crashed on me.  Unfortunately, it doesn't appear that these crashes are logged in the logs at all.  I think perhaps one thread that the miner is using crashes, leaving a zombie interface on the screen.

Also, I'm guessing that you want this type of feedback since you are distributing a debug version of the DLL's (and of the application itself, by extension.)

I'll post screenshots on this issue when I can get them.  It doesn't crash very often...and gets better and better with each revision.

**Comment by Blagodarenko** [comment]
thank you, screenshots will help finding the problems
