### ISSUE TITLE
Miner close by itself

### ISSUE THREAD

**Issue by ntzntz** [Blagodarenko/miner-burst#10]
Hi. I am not sure why and how is doing that. But today has closed on me like two times.
Do not know the reason.
I am running miner-v1.170601_AVX2.exe on I5-4460 8GB ram
It is possible?

**Comment by Blagodarenko** [comment]
Perhaps. Can you send to me blagodarenko@mail.ru last log file after close?

**Comment by Blagodarenko** [comment]
issue fixed. v1.170603
