### ISSUE TITLE
Wrong deadline

### ISSUE THREAD

**Issue by TestusRus** [Blagodarenko/miner-burst#13]
I found problem in v1.170603 with deadline information in "send" call:

16:16:02 found deadline=**889198** nonce=1692523 for account: xxxx file: xxxx_1234567_819200_819200
16:16:02 * GMI: Sent: POST /burst?requestType=getMiningInfo HTTP/1.0\r\nHost: poolofd32th.club:8124\r\nContent-Length: 0\r\nConnection: close\r\n\r\n
16:16:02 Sender: Sent: POST /burst?requestType=submitNonce&accountId=xxxx&nonce=1692523&deadline=**197901896069** HTTP/1.0\r\nHost: poolofd32th.club:8124\r\nX-Miner: Blago v1.170603\r\nX-Capacity: 14880\r\nContent-Length: 0\r\nConnection: close\r\n\r\n

16:16:18 found deadline=**793893** nonce=63274859 for account: xxxx file: xxxx_63126652_2048000_2048000
16:16:18 * GMI: Sent: POST /burst?requestType=getMiningInfo HTTP/1.0\r\nHost: poolofd32th.club:8124\r\nContent-Length: 0\r\nConnection: close\r\n\r\n
16:16:18 Sender: Sent: POST /burst?requestType=submitNonce&accountId=xxxx&nonce=63274859&deadline=**176690546488** HTTP/1.0\r\nHost: poolofd32th.club:8124\r\nX-Miner: Blago v1.170603\r\nX-Capacity: 14880\r\nContent-Length: 0\r\nConnection: close\r\n\r\n

22:15:32 found deadline=**344105** nonce=91995871 for account: xxxx file: xxxx_89980411_3145728_3145728
22:15:32 * GMI: Sent: POST /burst?requestType=getMiningInfo HTTP/1.0\r\nHost: poolofd32th.club:8124\r\nContent-Length: 0\r\nConnection: close\r\n\r\n
22:15:32 Sender: Sent: POST /burst?requestType=submitNonce&accountId=xxxx&nonce=91995871&deadline=**81549802264** HTTP/1.0\r\nHost: poolofd32th.club:8124\r\nX-Miner: Blago v1.170603\r\nX-Capacity: 14880\r\nContent-Length: 0\r\nConnection: close\r\n\r\n

**Comment by Blagodarenko** [comment]
It's not a problem. Miner send to the pool pure deadline, pool then divide it by baseTarget and got deadline (in seconds)
