### ISSUE TITLE
Can't read log file while miner works.

### ISSUE THREAD

**Issue by dmi3s** [Blagodarenko/miner-burst#14]
Could you plese open log file in a cooperative mode using _fsopen()? Just now as I can see you use fopen_s() and this function block reading log file until miner exit. File miner.cpp, line 28.

Thnx for your great job and good luck.

**Comment by Blagodarenko** [comment]
Fixed, thanks.

Спасибо за просмотр кода, исправил, в следующих версиях будет открываться.
