### ISSUE TITLE
No DL are found !!

### ISSUE THREAD

**Issue by Magdy-MA** [Blagodarenko/miner-burst#16]
Since the blockchain is attacked, the miner doesn't get me any DL although jminer is getting me plenty of shares and even good shares which is under 1 day the blago miner doesn't get them.
my plot size : 3.6 TB optimized
CPU : 7600K

Also the update add. and info add. are not working so well, many times the miner doesn't start because these add. are not working yet "miner-burst-1.160705" doesn't have this issue and runs even when the info and update add. is not working, so I have to mine in a pool and put another add. in the info and update add.

**Comment by Blagodarenko** [comment]
did you check "TargetDeadline" in conf?

**Comment by Magdy-MA** [comment]
Yes I did before I write this issue, I increased it to 1 year and nothing changed :(

**Comment by Magdy-MA** [comment]
This problem was solved by the new update (Y) (Y)
