### ISSUE TITLE
Miner Crashing v1.170820

### ISSUE THREAD

**Issue by sevencardz** [Blagodarenko/miner-burst#18]
After upgrading to 1.170820, the miner is crashing a few rounds after starting it.  I mine solo on a Ryzen 7 based system with the AVX2 exe on Win10.  If I use the older 1.170603 version, then the miner is stable for days.  I see no errors in the logs, just the generic windows "Application has stopped working" message.

**Comment by Blagodarenko** [comment]
see this issue https://github.com/Blagodarenko/miner-burst/issues/17
