### ISSUE TITLE
RCP API

### ISSUE THREAD

**Issue by Stoyvo** [Blagodarenko/miner-burst#2]
Is there an RCP API? 

I see rapidjson, however not sure if this is meant for RCP calls. 

If there is an API, can you provide documentation + examples?

**Comment by Blagodarenko** [comment]
rapidjson uses for parsing JSON from pool (wallet) and config.

Miner support (retranslate) only requests like:
if   "EnableProxy": true  and  "ProxyPort": 8126
http://127.0.0.1:8126/burst?requestType=getMiningInfo
http://127.0.0.1:8126/burst?requestType=submitNonce
