### ISSUE TITLE
chrome download

### ISSUE THREAD

**Issue by ew808** [Blagodarenko/miner-burst#22]
FYI Chrome is specifically blocking the 1.1708 version zip file from being downloaded because it's detecting a threat, but it is letting 1.1706 zip file download.
![image](https://user-images.githubusercontent.com/27975939/34084501-375df944-e347-11e7-8deb-4f2edb29c83f.png)

**Comment by jmuellers** [comment]
Same here, should I be worried?

**Comment by devksingh4** [comment]
From my experience, It is detecting a false positive from it thinking that the Miner is trying to access TOR (i believe). Regardless, the miner is safe to use and I am using it right now. Try using firefox or edge and if/when Defender or another AV blocks it, just whitelist.

**Comment by JohnDelisle** [comment]
@Blagodarenko I see you've closed the two issues asking about the AV issue.  Any chance you can comment on why your code is being flagged as carrying a trojan?

I'm sure you can appreciate we as miners are especially cautious about system integrity.. nothing worse than a stolen private key.

**Comment by Blagodarenko** [comment]
some times ago someone used my code for creating bot, and now some AV got  false positive.
https://www.virustotal.com/#/url/4611bb7d8f1928d7e634a39daa6373dc859ec768db38b8be838df9d84d51edb1/detection
