### ISSUE TITLE
Please add submitNonce parameter blockHeight

### ISSUE THREAD

**Issue by jasoncouture** [Blagodarenko/miner-burst#26]
creepMiner sends this parameter, I am writing pool software that makes use of this.
Please add it to your miner so I can stop saying it isn't supported.

**Comment by Blagodarenko** [comment]
yes, i'd add it for next version:
bytes = sprintf_s(buffer, buffer_size, "POST /burst?requestType=submitNonce&accountId=%llu&nonce=%llu&deadline=%llu&blockheight=%llu HTTP/1.0\r\nHost: %s:%s\r\nX-Miner: Blago %s\r\nX-Capacity: %llu\r\nContent-Length: 0\r\nConnection: close\r\n\r\n", iter->account_id, iter->nonce, iter->best, height, nodeaddr.c_str(), nodeport.c_str(), version, total);
