### ISSUE TITLE
UpdateInterval - what's this for please?

### ISSUE THREAD

**Issue by JohnDelisle** [Blagodarenko/miner-burst#27]
I'm wondering what this value signifies.  I'd like to reduce the frequency at which the miner re-reads my plots from disk.  At 30TB, this is a time and IO consuming activity.  

Is it possible to do this less frequently (I'm not adding new plots), without affecting my mining?  Thank you

**Comment by Blagodarenko** [comment]
try to change "CacheSize" - it's how many nonces will read per once.

"UpdateInterval" - ms, how often getMiningInfo from pool
