### ISSUE TITLE
Google Chrome blocking latest release, Windows Defender claims trojan

### ISSUE THREAD

**Issue by chadbaldwin** [Blagodarenko/miner-burst#28]
What's with the latest release being blocked by Chrome and Windows Defender? It says it has some sort of trojan in it. But the previous release is fine??

**Comment by chadbaldwin** [comment]
Looks like I created this ticket in duplicate to #22 however, it was closed with no comment and not fixed?

**Comment by Blagodarenko** [comment]
https://www.virustotal.com/#/url/4611bb7d8f1928d7e634a39daa6373dc859ec768db38b8be838df9d84d51edb1/detection
