### ISSUE TITLE
Sending same nonce more once

### ISSUE THREAD

**Issue by vervanda** [Blagodarenko/miner-burst#29]
Randomly a download I send will repeatedly send itself like 10 times, all on the exact time. I am using 1.170820 with pool.burstcoin.space. After the spam it doesn't send any confirmations (confirmed dl) from the last block. Then the next block may or may not do the same thing again.

**Comment by Blagodarenko** [comment]
Yes, miner try to reconfirm deadline if pool not accessible or too busy.

![reconfirm2](https://user-images.githubusercontent.com/6480287/35140410-299d4a14-fd08-11e7-90b8-9b9349e2bed7.JPG)
![reconfirmus2](https://user-images.githubusercontent.com/6480287/35140411-29bcc9f2-fd08-11e7-98f9-423d3fd86bb5.JPG)
![reconfirm](https://user-images.githubusercontent.com/6480287/35140412-29dd097e-fd08-11e7-9bbf-79c2b73e2284.JPG)
![reconfirmus](https://user-images.githubusercontent.com/6480287/35140413-29fba47e-fd08-11e7-814f-38419553a895.JPG)
